project_id = "ifvvxishlzlritdcjucf"

[functions.analyze-sentiment]
verify_jwt = false

[functions.scrape-news]
verify_jwt = false

[functions.lstm-prediction]
verify_jwt = false
[functions.get-live-rate]
enabled = true
verify_jwt = true
import_map = "./functions/get-live-rate/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-live-rate/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-live-rate/*.html" ]
